var tableauQuestion = [

	{   question : "Wat doe je als een politie agent je staande houdt?",
        propositionA : "Je rijdt zo snel mogenlijk weg.",
        propositionB : "Je stapt uit en trekt een wapen.",
        propositionC : "Je stop en gaat luisteren naar de agent.",
        propositionD : "Ik log uit ik haat politie.",
        reponse : "C"},

  	{   question : "Je bent in een achtervolging met de politie hoe handel je?",
        propositionA : "Ik rijd tegen het verkeer in en over heuvels om de politie te ontkomen.",
        propositionB : "k probeer ze af te schudden door na te denken en slim te spelen.",
		propositionC : "Ik schiet uit mijn auto om ze af te schudden.",
		propositionD : "Ik ga weg, rot politie en rot stad.",
        reponse : "B"},
    
    {   question : "De politie of iemand anders richt een wapen op je wat doe je?",
        propositionA : "Ik werk mee mijn leven heeft waarde.",
        propositionB : "Ik ben niet bang voor een pistool ik loop op hem af.",
		propositionC : "Wie denkt hij wel niet wie hij is ik zal hem een paar klappen verkopen.",
		propositionD : "Ik trek ook een wapen zonder normale roleplay en schiet hem dood.",
        reponse : "A"},
    
    {   question : "Je wordt door middel van de Benaderings Techniek Gevaarlijke Verdachte BTGV uit je voertuig gepraat. Er zijn vuurwapens op je gericht. Wat doe je?",
        propositionA : "Ik ben een ex commando ik regel het wel even ik bemoei me er dus mee.",
        propositionB : "Ik bel de politie er is een overval gaande.",
		propositionC : "Ik rijd er heen en doe mee, geld is geld.",
		propositionD : "Ik schiet alle agenten dood.",
        reponse : "B"},
    
    {   question : "Je bent in een RP scenario met de politie of iemand anders, je bent het er niet mee eens wat doe je?",
        propositionA : "Ik breek de roleplay en ga direct de confrontatie in.",
        propositionB : "Ik blijf in de roleplay en ga achteraf de discussie aan op discord.",
        propositionC : "Ik log uit en kom later weer.",
		propositionD : "Je gaat gewoon mee met de roleplay, soms win je niet.",
        reponse : "D"},
    
    {   question : "Wat is Veenstad?",
        propositionA : "Een server",
        propositionB : "Een game",
        propositionC : "Een stad",
        propositionD : "Een pixel",
        reponse : "C"},
    
    {   question : "Ik wil wapens kopen hoe ga ik dat doen?",
        propositionA : "Ik vraag op twitter hoeveel een pistool kost.",
        propositionB : "Ik rijd direct naar locaties waar wapens kunnen zijn.",
        propositionC : "Ik ga een gesprek aan met verschillende burgers misschien weten hun wat.",
        propositionD : "Ik ga mensen omver meppen om te hopen dat ze een wapen droppen.",
        reponse : "C"},
    
    {   question : "Ik zie een verlaten politie auto staan wat doe ik?",
        propositionA : "Ik rijd hem even een blokje om en daarna breng ik hem naar het politiebureau.",
        propositionB : "Ik pak mijn telefoon en stuur de politie een bericht met locatie.",
        propositionC : "Lekker stukje touren als een stoere kerel.",
        propositionD : "De auto laten staan, ik ben kapot lui.",
        reponse : "B"},

    {   question : "Ik zie een motor/auto staan in de shop maar er zitten geen kentekens op.",
        propositionA : "Zal wel een foutje zijn het staat er niet voor niks.",
        propositionB : "Ik kan er mee rijden maar ik weet dat het niet mag.",
        propositionC : "Kenteken wat is dat?",
		propositionD : "Een voertuig moet een kenteken hebben, anders is het niet legaal.",
        reponse : "D"},
    
    {   question : "Ik ben een agent en kan aan wapens komen, mijn vrienden willen ook wapens wat doe ik?",
        propositionA : "Ik wacht tot dat niemand oplet en geef de wapens aan hun.",
        propositionB : "Ik houd het volwassen en weet dat dit niet mag.",
        propositionC : "Weggeven? verkopen brengt meer op! ",
		propositionD : "Ik gooi honderden wapen op de grond, wie wil mag pakken!",
        reponse : "B"},
    
    {   question : "Ik rijd per ongeluk iemand dood wat doe ik?",
        propositionA : "Ik raak in paniek en rijd door.",
        propositionB : "Ik stop bekijk de situatie en vervolgens stuur ik de ambulance een bericht met locatie.",
		propositionC : "Moet hij maar niet op de weg lopen!",
		propositionD : "Ik trap nog een aantal keer na en loop weg.",
        reponse : "B"},
		
	{   question : "Ik ben dood gegaan (NEW LIFE) maar weet nog wel wie het heeft gedaan wat doe ik?",
        propositionA : "Zodra ik het ziekenhuis uit ben ga ik aangifte doen.",
        propositionB : "Ik zoek hem op en pakt hem terug.",
        propositionC : "Ik ben vergeten wat er is gebeurd en mag 15 minuten niet met roleplay meedoen.",
        propositionD : "Ik ga twitter vol spammen met tips.",
        reponse : "C"},
		
    {   question : "De ambulance was op tijd en ik ben opgeholpen na een beroving wat nu?",
        propositionA : "Ik ga aangiften doen.",
        propositionB : "Ik weet niks meer van de situatie",
        propositionC : "Ik sla de ambulance broeder want ik ben boos.",
        propositionD : "Ik sta op, voel niks geen pijn meer en ga mensen slaan.",
        reponse : "A"},
		
	{   question : "Ik ben in een Greenzone/Safezone, wat doe ik?",
        propositionA : "Ik mag niet vechten, schieten of andere illegale dingen doen.",
        propositionB : "Ik rijd iedereen dood.",
        propositionC : "Ik ga schieten!",
        propositionD : "Ik ga andere uitlokken om illegale activiteiten te doen in de Greenzone/Safezone.",
        reponse : "A"},
		
	{   question : "Ik wil een admin spreken, wat doe ik?",
        propositionA : "Ik zie hem staan en zeg dat ik uit karakter ben, hij zal en moet mij helpen.",
        propositionB : "Ik wacht netjes af todat hij vrij is, ik contacteer hem via discord of /ooc in de stad.",
        propositionC : "Twitter is de oplossing!",
        propositionD : "Wat is een admin?",
        reponse : "B"},
]