var tableauQuestion = [
    {   question : "Als je 80km/h gaat, en je bent op het punt om in een bebouwde kom te gaan, wat doe je dan?",
        propositionA : "Je versnelt",
        propositionB : "Je houdt je snelheid",
        propositionC : "Je gaat langzamer rijden",
        propositionD : "Je doet de deur open en springt uit de auto",
        reponse : "C"},

    {   question : "Als u bij een verkeerslicht rechtsaf slaat, maar een voetganger ziet, wat doet u dan?",
        propositionA : "Je passeert de voetganger",
        propositionB : "Je controleert of er geen andere voertuigen in de buurt zijn",
        propositionC : "Je wacht totdat de voetganger is overgestoken",
        propositionD : "Je schiet de voetganger en blijft rijden",
        reponse : "C"},

    {   question : "wat is de toegestane limiet binnen de bebouwde kom? (in GTA5)",
        propositionA : "80km/h",
        propositionB : "15km/h",
        propositionC : "40km/h",
        propositionD : "50km/h",
        reponse : "A"},

  {   question : "Voordat je van baan veranderd moet je eerst:",
        propositionA : "Je spiegels checken",
        propositionB : "Je blinde hoeken controlleren",
        propositionC : "Je knipperlicht aanzetten",
        propositionD : "Alles hierboven",
        reponse : "D"},

  {   question : "Alcohol en verkeer gaan niet samen. Voor bestuurders die korter dan 5 jaar hun rijbewijs hebben geldt een limiet van hoeveel promille?",
        propositionA : "0.5 promille.",
        propositionB : "0.10 promille.",
        propositionC : "0.2 promille.",
        propositionD : "1.0 promille.",
        reponse : "C"},

  {   question : "Wanneer kun je door blijven rijden bij een verkeerslicht?",
        propositionA : "Wanneer het groen is",
        propositionB : "Wanneer er niemand op de kruising is",
        propositionC : "Wanneer je in een school-zone bent",
        propositionD : "Wanneer het groen is en/ of rood en je naar rechts gaat",
        reponse : "D"},

  {   question : "Een voetganger heeft een ¨geen kruizing signaal¨, wat doe je??",
        propositionA : "Je laat hem passeren",
        propositionB : "Je observeert voordat je verder gaat",
        propositionC : "Je zwaait om te vertellen dat ze moeten oversteken",
        propositionD : "Je gaat verder omdat jou verkeerslicht groen is",
        reponse : "D"},

  {   question : "Wat is toegestaan bij het passeren van een ander voertuig",
        propositionA : "Je blijft dicht achter hem/haar om sneller te kunnen passeren",
        propositionB : "Je passeert het zonder de rijbaan te verlaten",
        propositionC : "Je rijdt aan de andere kant van de weg om te passeren",
        propositionD : "Je overschrijdt de snelheidslimiet om zo vooraan te komen",
        reponse : "C"},

  {   question : "Je rijdt op een snelweg waar je 120km/h mag. De meeste bestuurders rijden 125 km/h, dus moet je niet sneller rijden dan:",
        propositionA : "140 km/h",
        propositionB : "125 km/h",
        propositionC : "50 km/h",
        propositionD : "120 km/h",
        reponse : "D"},

  {   question : "Als je wordt ingehaald door iemand, wat moet je dan juist NIET doen?",
        propositionA : "Langzamer rijden",
        propositionB : "Je spiegels controlleren",
        propositionC : "Andere bestuurders in de gaten houden",
        propositionD : "Je snelheid verhogen",
        reponse : "D"},
]
